<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

function register_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.register':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This hook enables modules to register paths in order to define how URL requests are handled. Paths may be registered for URL handling only, or they can register a link to be placed in a menu (usually the Navigation menu). A path and its associated information is commonly called a "menu router item". This hook is rarely called (for example, when modules are enabled), and its results are cached in the database.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('Menu modules implementations return an associative array whose keys define paths and whose values are an associative array of properties for each path. (The complete list of properties is in the return value section below.)') . '</p>';
    return $output;
  }
}

function register_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'register/libraries_register';
}